# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-management
  labels:
    app: location-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-management
  template:
    metadata:
      labels:
        app: location-management
    spec:
      containers:
      - name: location-management
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

